CC = cc
FLAGS = -Wall -Werror -Wextra -g 
MLX = -lmlx -framework OpenGl -framework AppKit
MINIMLXLIB = lib/minilibx-linux/libmlx_linux.a
SRC = test_windows.c
OBJ = $(SRC:.c=.o)
NAME = fractol

%.c :%.o
	$(CC) -c $(FLAGS) -o
